name: nudishous_workspace
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  #app_shell
  - apps/nudishous_app

  #core
  - packages/core/core_logic
  - packages/core/core_lint
  - packages/core/core_ui
  - packages/core/core_i18n

  #data
  - packages/data/local_storage
  - packages/data/firebase_service
  - packages/data/openfood_api
  - packages/data/remote_api

  #feature
  - packages/features/sandbox
  - packages/features/profile
  - packages/features/auth
  - packages/features/settings

dev_dependencies:
  melos: ^7.5.1

dependency_overrides:
  #runner
  build_runner: ^2.4.0
  injectable_generator: ^2.4.4
  auto_route_generator: ^10.5.0

  # State
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3+1

  # DI
  get_it: ^9.2.1
  injectable: ^2.7.1+4

  # Utils
  equatable: ^2.0.8
  dartz: ^0.10.1

  # Network
  dio: ^5.9.2

  # Routing
  auto_route: ^11.1.0

  #storage
  shared_preferences: ^2.5.5

  #ui
  feather_icons: ^1.2.0


melos:
  scripts:
    analyze:
      run: melos exec -c 1 -- "flutter analyze ."
      description: Analyze semua package

    analyze:fix:
      run: melos exec -c 1 -- "dart fix --apply"
      description: Auto fix semua package

    lint:check:
      run: |
        melos exec -c 1 -- "flutter analyze . --fatal-infos --fatal-warnings"
      description: Cek lint strict mode — error jika ada warning

    outdated:
      run: melos exec -- "flutter pub outdated"
      description: Cek dependency yang outdated di semua package

    upgrade:
      run: melos exec -c 1 -- "flutter pub upgrade"
      description: Upgrade dependency di semua package

    test:
      exec: flutter test
      description: Menjalankan flutter test di semua package yang memiliki folder test.

    clean:
      run: melos exec -c 1 -- "flutter clean"
      description: "Membersihkan build files di seluruh package"

    format:
      exec: dart format .
      description: Melakukan formatting kode di seluruh workspace.

    generate:
      run: melos exec -c 1 --depends-on build_runner -- "dart run build_runner build --delete-conflicting-outputs"
      description: Menjalankan build_runner di semua package yang membutuhkannya.

    build:
      run: flutter pub run build_runner build --delete-conflicting-outputs
      exec:
        concurrency: 1