name: nudishous
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
resolution: workspace
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  #Feature
  auth: any
  sandbox: any
  profile: any

  #Core
  core_ui: any
  core_logic: any

  #data
  local_storage: any
  remote_api: any
  firebase_service: any

dev_dependencies:
  auto_route_generator: any
  injectable_generator: ^2.12.1
  build_runner: any


flutter:
  uses-material-design: true