name: core_ui
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace
homepage:

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  get_it: any
  injectable: any
  flutter_bloc: any
  auto_route: any

  google_fonts: ^8.0.2
  flutter_svg: ^2.2.4
  flutter_gen: ^5.14.0
  feather_icons: any

  core_logic: any
  core_i18n: any

  vector_graphics: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  core_lint:
    path: ../../core/core_lint
  injectable_generator: any
  build_runner: any
  flutter_gen_runner: ^5.14.0

flutter_gen:
  output: lib/src/generate
  line_length: 80
  integrations:
    flutter_svg: true
    rive: false
    lottie: false

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true # <- Add this line.
      class_name: AppAssets
      style: dot-delimiter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/images/
