name: core_logic
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace
homepage:

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  auto_route: ^11.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: any
  build_runner: any
  lean_builder: any
  flutter_lints: any

flutter:
  uses-material-design: true