name: core_logic
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace
homepage:

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  get_it: any
  injectable: any
  flutter_bloc: any

  #navigation
  auto_route: any

  #tools
  dartz: any
  dartx: any
  equatable: any

  package_info_plus: 9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  core_lint:
    path: ../../core/core_lint
  injectable_generator: any
  auto_route_generator: any
  build_runner: any

flutter:
  uses-material-design: true