name: profile
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace

homepage:

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: any
  injectable: any
  flutter_bloc: any
  auto_route: any
  dartz: any

  core_logic: any
  core_ui: any
  firebase_service: any
  local_storage: any
  remote_api: any

dev_dependencies:
  injectable_generator: any
  auto_route_generator: any
  build_runner: any

flutter:
  uses-material-design: true