name: Android Dev Build

on:
  push:
    branches:
      - develop

jobs:
  build-dev:
    runs-on: ubuntu-latest
    # Menggunakan environment 'development' agar sinkron dengan GitHub Secrets Anda
    environment: development

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4

      - name: 🐦 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          # Tentukan versi Flutter jika perlu agar konsisten dengan tim
          # flutter-version: '3.19.0'

      - name: 📦 Install Dependencies (Melos/Monorepo)
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: ⚙️ Run build_runner
        run: |
          melos generate

#      - name: 📋 Check Code Quality (Linting)
#        run: cd apps/nudishous_app && flutter analyze

#      - name: 🧪 Run Tests
#        run: cd apps/nudishous_app && flutter test

      - name: 🛠️ Create config.json from Secret
        # File ini dibuat di ROOT repository agar path ../../config.json di Android Studio tetap valid
        run: echo '${{ secrets.APP_CONFIG_JSON }}' > config.json

      - name: 🚀 Build APK Dev
        run: |
          cd apps/nudishous_app && flutter build apk --debug --flavor dev \
          -t lib/config/main_dev.dart \
          --dart-define-from-file=../../config.json

      - name: 📤 Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nudishous-dev-apk
          path: apps/nudishous_app/build/app/outputs/flutter-apk/app-dev-debug.apk