name: Android Dev Build

on:
  push:
    branches:
      - develop

jobs:
  build-dev:
    runs-on: ubuntu-latest
    # Menggunakan environment 'development' agar sinkron dengan GitHub Secrets Anda
    environment: development

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4

      - name: 🐦 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          # Tentukan versi Flutter jika perlu agar konsisten dengan tim
          # flutter-version: '3.19.0'

      - name: 📦 Install Dependencies (Melos/Monorepo)
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: ⚙️ Run build_runner
        run: |
          melos generate

#      - name: 📋 Check Code Quality (Linting)
#        run: cd apps/nudishous_app && flutter analyze

#      - name: 🧪 Run Tests
#        run: cd apps/nudishous_app && flutter test

      - name: 🔑 Restore Firebase Configuration
        # Kita petakan Secret ke Environment Variable agar aman dari parsing shell
        env:
          FB_DEV_CONTENT: ${{ secrets.FIREBASE_OPTIONS_DEV }}
          FB_PROD_CONTENT: ${{ secrets.FIREBASE_OPTIONS_PROD }}
          G_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
          APP_CONFIG_JSON: ${{ secrets.APP_CONFIG_JSON }}
        run: |
          # 1. Buat folder tujuan
          mkdir -p packages/data/firebase_service/lib/src/config/firebase_options/
          mkdir -p apps/nudishous_app/android/app/src/dev/
          
          # 2. Tulis file Dart menggunakan printf. 
          # printf "%s" lebih aman daripada echo untuk karakter spesial.
          printf "%s" "$FB_DEV_CONTENT" > packages/data/firebase_service/lib/src/config/firebase_options/firebase_options_dev.dart
          printf "%s" "$FB_PROD_CONTENT" > packages/data/firebase_service/lib/src/config/firebase_options/firebase_options_prod.dart
          
          # 3. Restore config.json
          printf "%s" "$APP_CONFIG_JSON" > config.json
          
          # 4. Decode google-services.json
          # Gunakan quotes pada variabel agar tidak dianggap command
          echo "$G_SERVICES_BASE64" | base64 --decode > apps/nudishous_app/android/app/src/dev/google-services.json

      - name: 🚀 Build APK Dev
        run: |
          cd apps/nudishous_app && flutter build apk --debug --flavor dev \
          -t lib/main.dart \
          --dart-define-from-file=../../config.json

      - name: 📤 Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nudishous-dev-apk
          path: apps/nudishous_app/build/app/outputs/flutter-apk/app-dev-debug.apk