name: Android Dev Build

on:
  push:
    branches:
      - develop

jobs:
  build-dev:
    runs-on: ubuntu-latest
    # Menggunakan environment 'development' agar sinkron dengan GitHub Secrets Anda
    environment: development

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4

      - name: 🐦 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          # Tentukan versi Flutter jika perlu agar konsisten dengan tim
          # flutter-version: '3.19.0'

      - name: 📦 Install Dependencies (Melos/Monorepo)
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: ⚙️ Run build_runner
        run: |
          melos generate

#      - name: 📋 Check Code Quality (Linting)
#        run: cd apps/nudishous_app && flutter analyze

#      - name: 🧪 Run Tests
#        run: cd apps/nudishous_app && flutter test

      - name: 🔑 Restore Firebase Configuration (Monorepo Style)
        run: |
          # 3. Tulis file Firebase Options Dev & Prod ke dalam PACKAGE
          echo "${{ secrets.FIREBASE_OPTIONS_DEV }}" > packages/data/firebase_service/lib/src/config/firebase_options/firebase_options_dev.dart
          echo "${{ secrets.FIREBASE_OPTIONS_PROD }}" > packages/data/firebase_service/lib/src/config/firebase_options/firebase_options_prod.dart
          
          # 4. Decode google-services.json ke dalam APP UTAMA
          echo "${{ secrets.GOOGLE_SERVICES_JSON_DEV }}" | base64 --decode > apps/nudishous_app/android/app/src/dev/google-services.json

      - name: 🛠️ Create config.json from Secret
        # File ini dibuat di ROOT repository agar path ../../config.json di Android Studio tetap valid
        run: echo '${{ secrets.APP_CONFIG_JSON }}' > config.json

      - name: 🚀 Build APK Dev
        run: |
          cd apps/nudishous_app && flutter build apk --debug --flavor dev \
          -t lib/main.dart \
          --dart-define-from-file=../../config.json

      - name: 📤 Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nudishous-dev-apk
          path: apps/nudishous_app/build/app/outputs/flutter-apk/app-dev-debug.apk